config-version: 2

name: "jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 275557

profile: default  # This should match the profile name in dbt Cloud, typically 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"
  load_source_data: true  # <--- Ensure this matches the seed config below

# 🔹 Seeds Configuration
seeds:
  jaffle_shop:
    +database: RAW       # ✅ Send seeds to RAW DB
    +schema: JAFFLE_DEV  # ✅ Match your Snowflake schema
    jaffle-data:
      +enabled: "{{ var('load_source_data', true) }}"

# 🔹 Models Configuration
models:
  jaffle_shop:
    +database: ANALYTICS     # ✅ All models go to ANALYTICS DB
    +schema: JAFFLE_DEV      # ✅ Match your Snowflake schema

    staging:
      +materialized: view    # Best for staging
    marts:
      +materialized: table   # Best for final outputs
